
FAIL Calling respondWith asynchronously throws an exception promise_test: Unhandled rejection with value: object "TypeError: null is not an object (evaluating 'worker.postMessage')"

